import {
	faArrowRight,
	faArrowRightArrowLeft,
	faArrowRotateRight,
	faArrowTrendUp,
	faBan,
	faBolt,
	faCalendarDays,
	faCartShopping,
	faChartColumn,
	faCheck,
	faCircleCheck,
	faCircleInfo,
	faClipboardList,
	faClockRotateLeft,
	faCoins,
	faDownload,
	faFaceSmileBeam,
	faFloppyDisk,
	faGaugeHigh,
	faHouse,
	faLayerGroup,
	faLightbulb,
	faLocationDot,
	faMagnifyingGlass,
	faMagnifyingGlassLocation,
	faMapLocationDot,
	faPenToSquare,
	faPlus,
	faReceipt,
	faRightFromBracket,
	faTableCells,
	faTicket,
	faTriangleExclamation,
	faTruck,
	faTruckFast,
	faUsers,
	faXmark	} from '@fortawesome/free-solid-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

/**
 * Registro de iconos de Font Awesome (solid) disponibles por nombre.
 * Único lugar donde se añaden iconos: Icon.svelte y los tests lo consumen.
 */
export const iconos: Record<string, IconDefinition> = {
	'arrow-right': faArrowRight,
	'arrows-left-right': faArrowRightArrowLeft,
	'arrow-rotate-right': faArrowRotateRight,
	'arrow-trend-up': faArrowTrendUp,
	ban: faBan,
	bolt: faBolt,
	'calendar-days': faCalendarDays,
	'cart-shopping': faCartShopping,
	'chart-column': faChartColumn,
	check: faCheck,
	'circle-check': faCircleCheck,
	'circle-info': faCircleInfo,
	'clipboard-list': faClipboardList,
	'clock-rotate-left': faClockRotateLeft,
	coins: faCoins,
	download: faDownload,
	'face-smile-beam': faFaceSmileBeam,
	'floppy-disk': faFloppyDisk,
	'gauge-high': faGaugeHigh,
	house: faHouse,
	'layer-group': faLayerGroup,
	lightbulb: faLightbulb,
	'location-dot': faLocationDot,
	'magnifying-glass': faMagnifyingGlass,
	'magnifying-glass-location': faMagnifyingGlassLocation,
	'map-location-dot': faMapLocationDot,
	'pen-to-square': faPenToSquare,
	plus: faPlus,
	receipt: faReceipt,
	'right-from-bracket': faRightFromBracket,
	'table-cells': faTableCells,
	ticket: faTicket,
	'triangle-exclamation': faTriangleExclamation,
	truck: faTruck,
	'truck-fast': faTruckFast,
	users: faUsers,
	xmark: faXmark
};
